version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-demo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pedidosdb
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
volumes:
  mysql_data:
